### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by zzstrwolf** [ShawnyXiao/2018-Kaggle-AdTrackingFraud#1]
正在学习你的kernel，不知道是否方便加个QQ或微信交流一下

**Comment by ShawnyXiao** [comment]
欢迎骚扰，QQ：772077730，麻烦备注一下~

**Comment by huazai-1994** [comment]
您好，我在运行你的代码时出现了下面情况，然后在网上搜也没找到解决方法
461]	training's auc: 0.985289
[462]	training's auc: 0.985297
Traceback (most recent call last):
  File "D:/Users/Administrator/PycharmProjects/2018-Kaggle-AdTrackingFraud/src/main.py", line 715, in <module>
    model_lgb, pred_lgb = lgb_predict(online_train_x, online_train_y, online_test_x, iterations_lgb, params_lgb)
  File "D:/Users/Administrator/PycharmProjects/2018-Kaggle-AdTrackingFraud/src/main.py", line 437, in lgb_predict
    predict = model.predict(test_feature)
  File "D:\Users\Administrator\Anaconda3\lib\site-packages\lightgbm\basic.py", line 1802, in predict
    return predictor.predict(data, num_iteration, raw_score, pred_leaf, pred_contrib, data_has_header, is_reshape)
  File "D:\Users\Administrator\Anaconda3\lib\site-packages\lightgbm\basic.py", line 406, in predict
    data = _data_from_pandas(data, None, None, self.pandas_categorical)[0]
  File "D:\Users\Administrator\Anaconda3\lib\site-packages\lightgbm\basic.py", line 273, in _data_from_pandas
    raise ValueError(msg + ', '.join(bad_fields))
ValueError: DataFrame.dtypes for data must be int, float or bool. Did not expect the data types in fields hour

**Comment by ShawnyXiao** [comment]
我这边用的是 Python2，不知道是不是这个原因导致的呢

**Comment by zzstrwolf** [comment]
你好 我使用main.py没能复现你的成绩，public 0.9799072 private 0.9806912，然后我尝试去掉最后的cvr变量，public 0.9802757 private 0.9810624。另外QQ麻烦通过以下，谢谢

**Comment by ShawnyXiao** [comment]
@zzstrwolf 那个结果最终还要和榜上一些之前别人公开的结果融合一下，才能到我之前的榜上成绩，具体的那些别人的开源结果我这边没有保留了，你可以去kaggle上找找
